# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1014, 589)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0.3125 rgba(203, 81, 164, 255), stop:0.869318 rgba(237, 108, 79, 255));\n"
"\n"
"border-radius: 15px;\n"
"border: 1px solid #000000;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.titulo = QtWidgets.QLabel(self.frame)
        self.titulo.setGeometry(QtCore.QRect(150, 30, 711, 71))
        self.titulo.setStyleSheet("font: 81 20pt \"Rockwell Extra Bold\";\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0.357955 rgba(160, 108, 169, 248), stop:0.869318 rgba(237, 221, 154, 255));\n"
"border: 3px solid #000000")
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.img = QtWidgets.QLabel(self.frame)
        self.img.setGeometry(QtCore.QRect(580, 140, 411, 361))
        self.img.setStyleSheet("background-color: rgb(0, 0, 0,0%);\n"
"border:5px solid #000000\n"
"")
        self.img.setText("")
        self.img.setPixmap(QtGui.QPixmap("imgVentilador.jpg"))
        self.img.setScaledContents(True)
        self.img.setObjectName("img")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 110, 531, 371))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(8)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setStyleSheet("font: 63 12pt \"Sitka Text Semibold\";\n"
"background-color: rgb(255, 205, 247);\n"
"border-radius: 0px;\n"
"border: 2px solid #000000\n"
"")
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setIndent(0)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.velocidad_angular = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.velocidad_angular.setStyleSheet("border-radius: 0px;\n"
"border: 2px solid #000000;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Segoe UI Variable\";\n"
"padding: 10px;")
        self.velocidad_angular.setAlignment(QtCore.Qt.AlignCenter)
        self.velocidad_angular.setObjectName("velocidad_angular")
        self.gridLayout.addWidget(self.velocidad_angular, 5, 1, 1, 1)
        self.angulo_inicial = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.angulo_inicial.setStyleSheet("border-radius: 0px;\n"
"border: 2px solid #000000;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Segoe UI Variable\";\n"
"padding: 10px;")
        self.angulo_inicial.setAlignment(QtCore.Qt.AlignCenter)
        self.angulo_inicial.setObjectName("angulo_inicial")
        self.gridLayout.addWidget(self.angulo_inicial, 4, 1, 1, 1)
        self.coeficiente_c = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.coeficiente_c.setStyleSheet("border-radius: 0px;\n"
"border: 2px solid #000000;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Segoe UI Variable\";\n"
"padding: 10px;")
        self.coeficiente_c.setAlignment(QtCore.Qt.AlignCenter)
        self.coeficiente_c.setObjectName("coeficiente_c")
        self.gridLayout.addWidget(self.coeficiente_c, 8, 1, 1, 1)
        self.coeficiente_k = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.coeficiente_k.setStyleSheet("border-radius: 0px;\n"
"border: 2px solid #000000;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Segoe UI Variable\";\n"
"padding: 10px;")
        self.coeficiente_k.setAlignment(QtCore.Qt.AlignCenter)
        self.coeficiente_k.setObjectName("coeficiente_k")
        self.gridLayout.addWidget(self.coeficiente_k, 7, 1, 1, 1)
        self.radio = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.radio.setStyleSheet("border-radius: 0px;\n"
"border: 2px solid #000000;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Segoe UI Variable\";\n"
"padding: 10px;")
        self.radio.setAlignment(QtCore.Qt.AlignCenter)
        self.radio.setObjectName("radio")
        self.gridLayout.addWidget(self.radio, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setStyleSheet("font: 63 12pt \"Sitka Text Semibold\";\n"
"background-color: rgb(255, 205, 247);\n"
"border-radius: 0px;\n"
"border: 2px solid #000000")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setStyleSheet("font: 63 12pt \"Sitka Text Semibold\";\n"
"background-color: rgb(255, 205, 247);\n"
"border-radius: 0px;\n"
"border: 2px solid #000000")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setStyleSheet("font: 63 12pt \"Sitka Text Semibold\";\n"
"background-color: rgb(255, 205, 247);\n"
"border-radius: 0px;\n"
"border: 2px solid #000000")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setStyleSheet("font: 63 12pt \"Sitka Text Semibold\";\n"
"background-color: rgb(255, 205, 247);\n"
"border-radius: 0px;\n"
"border: 2px solid #000000")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 7, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setStyleSheet("font: 63 12pt \"Sitka Text Semibold\";\n"
"background-color: rgb(255, 205, 247);\n"
"border-radius: 0px;\n"
"border: 2px solid #000000")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setStyleSheet("font: 63 12pt \"Sitka Text Semibold\";\n"
"background-color: rgb(255, 205, 247);\n"
"border-radius: 0px;\n"
"border: 2px solid #000000")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.inercia = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.inercia.setStyleSheet("border-radius: 0px;\n"
"border: 2px solid #000000;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Segoe UI Variable\";\n"
"padding: 10px;\n"
"")
        self.inercia.setCursorPosition(0)
        self.inercia.setAlignment(QtCore.Qt.AlignCenter)
        self.inercia.setDragEnabled(False)
        self.inercia.setObjectName("inercia")
        self.gridLayout.addWidget(self.inercia, 1, 1, 1, 1)
        self.tipo_torque = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.tipo_torque.setStyleSheet("border-radius: 0px;\n"
"border: 2px solid #000000;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Segoe UI Variable\";\n"
"padding: 10px;")
        self.tipo_torque.setCurrentText("")
        self.tipo_torque.setObjectName("tipo_torque")
        self.gridLayout.addWidget(self.tipo_torque, 6, 1, 1, 1)
        self.ecuacion_diferencial = QtWidgets.QPushButton(self.frame)
        self.ecuacion_diferencial.setGeometry(QtCore.QRect(30, 490, 241, 71))
        self.ecuacion_diferencial.setStyleSheet("QPushButton{\n"
"border: 3px solid #000000;\n"
"background-color: qlineargradient(spread:pad, x1:0.618909, y1:0.119,                              x2:0.597, y2:0.909091, stop:0.357955 rgba(101, 168, 182, 201), stop:0.607955 rgba(118, 129, 207, 212));\n"
"font: 63 13pt \"Segoe UI Variable Text Semibold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:0, y2:1, stop:0.357955 rgba(227, 79, 79, 155), stop:0.613636 rgba(246, 189, 69, 189));\n"
"border: 3px solid #000000;\n"
"}")
        self.ecuacion_diferencial.setObjectName("ecuacion_diferencial")
        self.graficar = QtWidgets.QPushButton(self.frame)
        self.graficar.setGeometry(QtCore.QRect(310, 490, 241, 71))
        self.graficar.setStyleSheet("QPushButton{\n"
"border: 3px solid #000000;\n"
"background-color: qlineargradient(spread:pad, x1:0.618909, y1:0.119,                              x2:0.597, y2:0.909091, stop:0.357955 rgba(101, 168, 182, 201), stop:0.607955 rgba(118, 129, 207, 212));\n"
"font: 63 13pt \"Segoe UI Variable Text Semibold\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:0, y2:1, stop:0.357955 rgba(227, 79, 79, 155), stop:0.613636 rgba(246, 189, 69, 189));\n"
"border: 3px solid #000000;\n"
"}")
        self.graficar.setObjectName("graficar")
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titulo.setText(_translate("MainWindow", "MOVIMIENTO CIRCULAR VENTILADOR"))
        self.label_3.setText(_translate("MainWindow", "Momento de inercia (I)"))
        self.velocidad_angular.setPlaceholderText(_translate("MainWindow", "Velocidad de rotación (rad/s)"))
        self.angulo_inicial.setPlaceholderText(_translate("MainWindow", "Posición inical (rad) "))
        self.coeficiente_c.setPlaceholderText(_translate("MainWindow", "Ingrese el comportamiento de W₀"))
        self.coeficiente_k.setPlaceholderText(_translate("MainWindow", "Ingrese el comportamiento de V₀"))
        self.radio.setPlaceholderText(_translate("MainWindow", "Radio (m)"))
        self.label_6.setText(_translate("MainWindow", "Ángulo inicial (θ₀)"))
        self.label_7.setText(_translate("MainWindow", "Velocidad Angular Inicial (ω₀)"))
        self.label_8.setText(_translate("MainWindow", "Tipo de Torque"))
        self.label_9.setText(_translate("MainWindow", "Coeficiente (K)"))
        self.label_5.setText(_translate("MainWindow", "Coeficiente (c)"))
        self.label_4.setText(_translate("MainWindow", "Radio (r)"))
        self.inercia.setPlaceholderText(_translate("MainWindow", "Resistencia (kg·m²) "))
        self.ecuacion_diferencial.setText(_translate("MainWindow", "Definir Ecuación Diferencial"))
        self.graficar.setText(_translate("MainWindow", "Graficar"))
